Resolve #152: Fix AppImageLauncher integration problems (#153)
# Description
On Fedora, I was seeing the following error:
```
ERROR: appimage_register_in_system : Icon field contains path
```

This problem is fixed by (1) providing an icon at the root of the
appimage directory, AND (2) in the .desktop file, only providing the
icon's filename with no extension.

Closes #152.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Test 1

**Test Configuration**: Built on Ubuntu 20.04, installed on Fedora 39.
No errors.

# Checklist:

- [x] My code follows the style guidelines of this project (`black` for
Python
  code, `.clang-format` in the `src/jyut-dict` directory for C++)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have translated my user-facing strings to all
currently-supported languages
- [x] I have made corresponding changes to the documentation